2018-09-05 12:20:24,019 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:20:39,088 - __main__ - INFO - 请求足球url失败,date:2018-08-23
2018-09-05 12:20:44,500 - __main__ - INFO - 请求足球url失败,date:2018-08-24
2018-09-05 12:20:44,540 - __main__ - INFO - 请求足球url失败,date:2018-08-25
2018-09-05 12:20:44,581 - __main__ - INFO - 请求足球url失败,date:2018-08-26
2018-09-05 12:20:44,621 - __main__ - INFO - 请求足球url失败,date:2018-08-27
2018-09-05 12:20:44,663 - __main__ - INFO - 请求足球url失败,date:2018-08-28
2018-09-05 12:20:44,703 - __main__ - INFO - 请求足球url失败,date:2018-08-29
2018-09-05 12:20:44,747 - __main__ - INFO - 请求足球url失败,date:2018-08-30
2018-09-05 12:20:44,789 - __main__ - INFO - 请求足球url失败,date:2018-08-31
2018-09-05 12:20:44,832 - __main__ - INFO - 请求足球url失败,date:2018-09-01
2018-09-05 12:21:25,342 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:21:26,605 - __main__ - ERROR - 请求足球url失败,date:2018-08-23
Traceback (most recent call last):
  File "D:/python-project/newbee/stock/football/football.py", line 39, in get_content_sh
    url_content = urllib2.urlopen(req).read().decode('utf-8')
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 886, in _send_output
    self.send(message_body)
  File "C:\Python27\lib\httplib.py", line 858, in send
    self.sock.sendall(data)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: sendall() argument 1 must be string or buffer, not dict
2018-09-05 12:21:51,674 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:27:23,598 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:29:02,990 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:29:56,318 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:31:04,716 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:31:30,335 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:34:44,150 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:35:42,515 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:38:40,223 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:39:56,237 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 12:40:57,819 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
2018-09-05 14:13:10,721 - __main__ - INFO - 开始爬取数据 start:2018-08-23,end:2018-09-01
